name: Flutter Android

on:
  workflow_dispatch:
  push:
    tags: [ '*' ]
  pull_request:
    branches: [ main ]
    types: [ assigned ]
    paths-ignore:
      - '**/.gitignore'
      - '**/*.md'

jobs:
  flutter_build_android:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        flutter-project-dir: [ ./packages/hello_world ]
        flutter-channel: [ stable ]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: ${{ matrix.flutter-channel }}
          cache: true

      - name: Check up SDKs
        run: |
          dart --version
          flutter --version

      - name: Fetch Flutter Dependency Packages
        run: flutter pub get
        working-directory: ${{ matrix.flutter-project-dir }}

      - name: Build Apk
        run: |
          flutter build apk
        working-directory: ${{ matrix.flutter-project-dir }}

      - name: Build App Bundle
        run: |
          flutter build appbundle
        working-directory: ${{ matrix.flutter-project-dir }}

      - name: Upload Android
        if: ${{ github.event_name == 'workflow_dispatch' }}
        uses: actions/upload-artifact@v3
        with:
          name: Android
          path: |
            ${{ matrix.flutter-project-dir }}/build/app/outputs/bundle/release
            ${{ matrix.flutter-project-dir }}/build/app/outputs/apk/release
